# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'error_scr.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_error_scr(object):
    def setupUi(self, error_scr):
        error_scr.setObjectName("error_scr")
        error_scr.setWindowModality(QtCore.Qt.ApplicationModal)
        error_scr.resize(373, 108)
        font = QtGui.QFont()
        font.setPointSize(11)
        error_scr.setFont(font)
        error_scr.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        error_scr.setModal(True)
        self.Warn_Ico = QtWidgets.QLabel(error_scr)
        self.Warn_Ico.setGeometry(QtCore.QRect(10, 10, 101, 91))
        self.Warn_Ico.setText("")
        self.Warn_Ico.setObjectName("Warn_Ico")
        self.Error_Out = QtWidgets.QLabel(error_scr)
        self.Error_Out.setGeometry(QtCore.QRect(124, 5, 241, 61))
        self.Error_Out.setText("")
        self.Error_Out.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Error_Out.setWordWrap(True)
        self.Error_Out.setObjectName("Error_Out")
        self.Btn = QtWidgets.QPushButton(error_scr)
        self.Btn.setGeometry(QtCore.QRect(140, 70, 93, 31))
        self.Btn.setObjectName("Btn")

        self.retranslateUi(error_scr)
        self.Btn.clicked.connect(error_scr.exec) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(error_scr)

    def retranslateUi(self, error_scr):
        _translate = QtCore.QCoreApplication.translate
        error_scr.setWindowTitle(_translate("error_scr", "Ошибка"))
        self.Btn.setText(_translate("error_scr", "Понятно"))
